# Generated by Django 4.1.6 on 2023-03-08 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 8, 19, 0, 13, 876404, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
