# Generated by Django 4.1.6 on 2023-03-08 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_question_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 8, 17, 57, 39, 471773, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
