# Generated by Django 4.1.6 on 2023-03-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_alter_question_date_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
